language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
      - sourceline: 'deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
      - sourceline: 'deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libsodium-dev

before_script:
  - |
      export PATH=$HOME/.local/bin:$PATH
      export LIBRARY_PATH=$HOME/lib
      export LD_LIBRARY_PATH=$HOME/lib
      export PKG_CONFIG_PATH=$HOME/lib/pkgconfig

      curl -sSOL https://github.com/zeromq/libzmq/releases/download/v4.2.0/zeromq-4.2.0.tar.gz
      tar zxf zeromq-4.2.0.tar.gz
      cd zeromq-4.2.0
      ./autogen.sh
      ./configure --prefix=$HOME --with-libsodium
      make && make install
      cd ..

      curl -sSOL https://github.com/zeromq/czmq/releases/download/v4.0.1/czmq-4.0.1.tar.gz
      tar zxf czmq-4.0.1.tar.gz
      cd czmq-4.0.1
      ./configure --prefix=$HOME
      make && make install
      cd $TRAVIS_BUILD_DIR

script:
  - cargo build --verbose
  - cargo test --verbose
  - |
      ln -s "$HOME/lib/libczmq.so.4" target/debug
      ln -s "$HOME/lib/libzmq.so.5" target/debug

      cd bindings

      for VER in 5 7
      do
        cd "php$VER"
        ln -s ../c include
        phpize
        ./configure --with-inapi=../../target/debug
        make
        TEST_PHP_ARGS="-q" make test || exit 1
        cd ..
      done

      cd ..

env:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
