sudo: required
dist: trusty
language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
      - sourceline: 'deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
      - sourceline: 'deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libsodium-dev
      - php5

before_script:
  - |
      pip install 'travis-cargo<0.2' --user

      export PATH=$HOME/.local/bin:$PATH
      export LIBRARY_PATH=$HOME/lib
      export LD_LIBRARY_PATH=$HOME/lib
      export PKG_CONFIG_PATH=$HOME/lib/pkgconfig

      cd /tmp

      curl -sSOL https://github.com/zeromq/zeromq4-1/archive/v4.1.5.tar.gz
      tar zxf v4.1.5.tar.gz
      cd zeromq4-1-4.1.5
      ./autogen.sh
      ./configure --prefix=$HOME --with-libsodium --silent
      make --silent
      make --silent install
      cd ..

      git clone https://github.com/zeromq/czmq
      cd czmq
      ./autogen.sh
      ./configure --prefix=$HOME --silent
      make --silent
      make --silent install
      cd $TRAVIS_BUILD_DIR

script:
  - travis-cargo build
  - travis-cargo test
  - |
      ln -s "$HOME/lib/libczmq.so.3" target/debug
      ln -s "$HOME/lib/libzmq.so.5" target/debug

      cd bindings

      for VER in 5 7
      do
        cd "php$VER"
        ln -s ../c include
        phpize
        ./configure --with-inapi=../../target/debug --silent
        make --silent
        TEST_PHP_ARGS="-q" make test || exit 1
        cd ..
      done

      cd ..

after_success:
  - travis-cargo coveralls --no-sudo --verify --exclude-pattern="/tmp/,/usr/"

env:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
