[package]

name = "intecture-api"
version = "0.0.2"
authors = [ "Peter Hayes <peter.hayes@betweenlines.co.uk>" ]
license = "MPL-2.0"
description = "API component for Intecture infrastructure. Intecture is the developer friendly, multi-lingual configuration management tool."
keywords = ["intecture", "api"]
homepage = "https://intecture.io"
repository = "https://github.com/betweenlines/intecture-api"
build = "build.rs"

[dependencies]

intecture-host-primitives = { git = "https://github.com/betweenlines/intecture-host-primitives.git" }
lazy_static = "0.1.*"
libc = "0.2.*"
rustc-serialize = "0.3.*"
zmq = { git = "https://github.com/petehayes102/rust-zmq.git" }
zmq-sys = "*"

[lib]

name = "inapi"
crate_type = [ "rlib", "dylib" ]